# Generated by Django 2.2 on 2019-05-06 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
    ]
